[package]
name = "llh"
version = "0.1.0"
authors = ["Elen Eisendle <ln@calcifer.ee>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.8", features = ["json", "blocking"] }
tokio = { version = "0.2.22", features = ["full", "macros"] }
select = "0.5.0"
chrono = "0.4.19"
serde_json = "1.0.58"
serde = {version = "1.0.116", features = ["derive"]}
